// Cross-runtime parity gate: the JS port must produce bit-identical
// output to Python on every fixture entry.
//
// Run from anywhere:    node --test viewer/test/
// Or from viewer/:      npm test
//
// Fixture is regenerated by:
//   python -m plant_sim.runtime._emit_vectors > tests/fixtures/pcg_vectors.json
//
// If this test fails, the JS port and Python implementation drifted.
// Fix whichever side is wrong, regenerate the fixture if intentional, and
// land both sides in the same commit.

import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import { seededRng } from "../pcg.js";
import { Seed } from "../seed.js";

const FIXTURE_URL = new URL(
  "../../tests/fixtures/pcg_vectors.json",
  import.meta.url,
);
const fixture = JSON.parse(readFileSync(FIXTURE_URL, "utf8"));

test("fixture version matches expected schema", () => {
  assert.equal(fixture.version, 1);
  assert.equal(fixture.draws_per_seed, 1000);
  assert.ok(fixture.pcg_seeds.length >= 100);
  assert.ok(fixture.derive_cases.length >= 20);
});

test("PCG output bit-equal across all fixture seeds", () => {
  for (const entry of fixture.pcg_seeds) {
    const rng = seededRng(entry.seed);
    const h = createHash("sha256");
    for (let i = 0; i < fixture.draws_per_seed; i++) {
      const u = rng.nextU64();
      const buf = Buffer.alloc(8);
      buf.writeBigUInt64BE(u, 0);
      h.update(buf);
      if (i < fixture.first_n_verbatim) {
        const hex = u.toString(16).padStart(16, "0");
        assert.equal(
          hex,
          entry.first_n[i],
          `seed ${entry.seed} draw ${i}: JS got ${hex}, fixture has ${entry.first_n[i]}`,
        );
      }
    }
    assert.equal(
      h.digest("hex"),
      entry.sha256,
      `seed ${entry.seed}: full-stream sha256 mismatch`,
    );
  }
});

test("Seed.derive output bit-equal across all fixture cases", async () => {
  for (const entry of fixture.derive_cases) {
    const parent = new Seed(entry.parent);
    const salts = entry.salts.map((s) => {
      if (s.type === "str") return s.value;
      if (s.type === "int") return BigInt(s.value); // value is decimal string
      throw new Error(`unknown salt type: ${s.type}`);
    });
    const child = await parent.derive(...salts);
    assert.equal(
      child.canonical(),
      entry.child,
      `derive(${entry.parent}, ${JSON.stringify(entry.salts)}): JS got ${child.canonical()}, fixture has ${entry.child}`,
    );
  }
});
